name: Run MSTest Tests (Local & CI)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: List all tests
        run: dotnet test testTheThing/testTheThing.csproj --list-tests -v normal

      - name: Run all tests
        run: dotnet test testTheThing/testTheThing.csproj --no-build --verbosity normal

      - name: Run specific timer test
        run: >
          dotnet test testTheThing/testTheThing.csproj
          --no-build
          --filter "Name=EsperaTresSegundosYLoguea"
          --verbosity normal
