name: Run MSTest Tests (Local & CI)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Allow PowerShell scripts (scope = this job)
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
          Get-ExecutionPolicy -List
    

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: List tests
        run: dotnet test testTheThing/testTheThing.csproj --list-tests -v normal

      - name: Run all tests
        run: dotnet test testTheThing/testTheThing.csproj --no-build --verbosity normal

      - name: Run specific timer test
        run: >
          dotnet test testTheThing/testTheThing.csproj
          --no-build
          --filter "Name=EsperaTresSegundosYLoguea"
          --verbosity normal
