name: Run MSTest Tests (Local & CI)

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      testFilter:
        description: "Filtro MSTest (opcional), ej: Name=prueba_.*"
        required: false
        default: ""
      notes:
        description: "Comentario (quién lanzó, etc.)"
        required: false
        default: ""

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]

    concurrency:
      group: local-runner
      cancel-in-progress: false

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: List tests
        run: dotnet test testTheThing/testTheThing.csproj --list-tests -v normal

      - name: Run all tests (with optional filter)
        run: >
          dotnet test testTheThing/testTheThing.csproj
          --no-build
          --configuration Release
          ${{ inputs.testFilter != '' && format('--filter "{0}"', inputs.testFilter) || '' }}
          --verbosity normal
