name: Run MSTest Tests (Local & CI)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: List tests
        run: dotnet test testTheThing/testTheThing.csproj --list-tests -v normal

      - name: Run all tests
        run: dotnet test testTheThing/testTheThing.csproj --no-build --configuration Release --verbosity normal
