- name: Generate .runsettings from inputs
shell: cmd
run: >
  powershell -NoProfile -ExecutionPolicy Bypass -Command
  "$xml = @'
  <?xml version=""1.0"" encoding=""utf-8""?>
  <RunSettings>
    <RunConfiguration>
      <ResultsDirectory>.\test_results</ResultsDirectory>
    </RunConfiguration>
    <TestRunParameters>
      <Parameter name=""CameraIp""   value=""${{ inputs.CameraIp || '127.0.0.1' }}"" />
      <Parameter name=""DelayMs""    value=""${{ inputs.DelayMs  || '1500' }}"" />
      <Parameter name=""ShouldFail"" value=""${{ inputs.ShouldFail || 'false' }}"" />
    </TestRunParameters>
  </RunSettings>
  '@; Set-Content -Path runsettings.test.runsettings -Value $xml -Encoding utf8"

- name: Run all tests (with .runsettings)
run: >
  dotnet test testTheThing/testTheThing.csproj
  --no-build
  --configuration Release
  ${{ inputs.testFilter != '' && format('--filter "{0}"', inputs.testFilter) || '' }}
  --logger "trx;LogFileName=test_results.trx"
  --results-directory ./test_results
  --settings runsettings.test.runsettings
